routes:
  /advertise/:
    template: page-advertise
    data: page.advertise

collections:
  /watch/:
    permalink: /watch/{slug}/
    template: index-watch
    filter: primary_tag:watch

  /listen/:
    permalink: /listen/{slug}/
    template: index-listen
    filter: primary_tag:listen

  /read/:
    permalink: /read/{slug}/
    template: index-read
    filter: primary_tag:read

  /courses/:
    permalink: /courses/{slug}/
    template: index-courses
    filter: primary_tag:courses

  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
