routes:
  /advertise/:
    template: page-advertise
    data: page.advertise

  /listen/rss/:
    template: listen-rss
    content_type: text/xml

  /service-worker/:
    template: sw
    content_type: application/javascript

  /listen/shows/:
    template: index-listen-shows

collections:
  /watch/:
    permalink: /watch/{slug}/
    template: index-watch
    filter: primary_tag:watch

  /listen/shows/krino-politics-podcast/:
    permalink: /listen/shows/krino-politics-podcast/{slug}/
    template: index-listen-show-krino-politics-podcast
    filter: primary_tag:listen+tag:krino-politics-podcast

  /listen/shows/on-the-record/:
    permalink: /listen/shows/on-the-record/{slug}/
    template: index-listen-show-on-the-record
    filter: primary_tag:listen+tag:on-the-record

  /listen/shows/breaking-points/:
    permalink: /listen/shows/breaking-points/{slug}/
    template: index-listen-show-breaking-points
    filter: primary_tag:listen+tag:breaking-points

  /listen/shows/the-fact-check/:
    permalink: /listen/shows/the-fact-check/{slug}/
    template: index-listen-show-the-fact-check
    filter: primary_tag:listen+tag:the-fact-check

  /listen/shows/cross-examined/:
    permalink: /listen/shows/cross-examined/{slug}/
    template: index-listen-show-cross-examined
    filter: primary_tag:listen+tag:cross-examined

  /listen/:
    permalink: /listen/{slug}/
    template: index-listen
    filter: primary_tag:listen

  /read/essays/:
    permalink: /read/essays/{slug}/
    template: index-read-essays
    filter: primary_tag:read+tag:essays

  /read/fiction/:
    permalink: /read/fiction/{slug}/
    template: index-read-fiction
    filter: primary_tag:read+tag:fiction

  /read/poems/:
    permalink: /read/poems/{slug}/
    template: index-read-poems
    filter: primary_tag:read+tag:poems

  /read/book-review/:
    permalink: /read/book-review/{slug}/
    template: index-read-book-review
    filter: primary_tag:read+tag:book-review

  /read/:
    permalink: /read/{slug}/
    template: index-read
    filter: primary_tag:read

  /learn/:
    permalink: /learn/{slug}/
    template: index-learn
    filter: primary_tag:learn

  /shop/reports/:
    permalink: /shop/reports/{slug}/
    template: index-shop-reports
    filter: primary_tag:shop+tag:reports

  /shop/merch/:
    permalink: /shop/merch/{slug}/
    template: index-shop-merch
    filter: primary_tag:shop+tag:merch

  /shop/certificates/:
    permalink: /shop/certificates/{slug}/
    template: index-shop-certificates
    filter: primary_tag:shop+tag:certificates

  /shop/:
    permalink: /shop/{slug}/
    template: index-shop
    filter: primary_tag:shop

  /stream/:
    permalink: /stream/{slug}/
    template: index-stream
    filter: primary_tag:stream

  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
