routes:
  /advertise/:
    template: page-advertise
    data: page.advertise

  /listen/rss/:
    template: listen-rss
    content_type: text/xml

  /service-worker/:
    template: sw
    content_type: application/javascript

collections:
  /watch/:
    permalink: /watch/{slug}/
    template: index-watch
    filter: primary_tag:watch

  /listen/:
    permalink: /listen/{slug}/
    template: index-listen
    filter: primary_tag:listen

  /read/essays/:
    permalink: /read/essays/{slug}/
    template: index-read-essays
    filter: primary_tag:read+tag:essays

  /read/fiction/:
    permalink: /read/fiction/{slug}/
    template: index-read-fiction
    filter: primary_tag:read+tag:fiction

  /read/poems/:
    permalink: /read/poems/{slug}/
    template: index-read-poems
    filter: primary_tag:read+tag:poems

  /read/book-review/:
    permalink: /read/book-review/{slug}/
    template: index-read-book-review
    filter: primary_tag:read+tag:book-review

  /read/:
    permalink: /read/{slug}/
    template: index-read
    filter: primary_tag:read

  /learn/:
    permalink: /learn/{slug}/
    template: index-learn
    filter: primary_tag:learn

  /shop/reports/:
    permalink: /shop/reports/{slug}/
    template: index-shop-reports
    filter: primary_tag:shop+tag:reports

  /shop/merch/:
    permalink: /shop/merch/{slug}/
    template: index-shop-merch
    filter: primary_tag:shop+tag:merch

  /shop/certificates/:
    permalink: /shop/certificates/{slug}/
    template: index-shop-certificates
    filter: primary_tag:shop+tag:certificates

  /shop/:
    permalink: /shop/{slug}/
    template: index-shop
    filter: primary_tag:shop

  /stream/:
    permalink: /stream/{slug}/
    template: index-stream
    filter: primary_tag:stream

  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
